---
- name: Delete OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    guid: "{{ lookup('env','GUID') }}"
  
  tasks:
  - name: Collection instance info
    os_server_info:
      cloud: "{{ guid }}-project"
    register: os_servers_instances
  
  - name: Wait for servers to be available
    debug:
      var: item.private_v4
    when: item.metadata.AnsibleGroup == "haproxy_balancers"  or item.metadata.AnsibleGroup == "backend_servers"  or item.metadata.AnsibleGroup == "postgres_servers"  
    loop: "{{ os_servers_instances.openstack_servers }}"

      
  - name: Wait for servers to be available
    wait_for:
      host: "{{ os_servers_instances.openstack_servers[0].private_v4 }}"
      port: 22
      search_regex: OpenSSH
      timeout: 10      
