- name: Play to automate process
  hosts: all
  become: yes
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      delegate_facts: true
      delegate_to: localhost
      connection: local
      register: netfacts
      
    - name: presentar datos
      debug:
        var: netfacts 
