---
- name: Delete OpenStack Instances
  hosts: control_node
  gather_facts: true
  vars:
    guid: "{{ lookup('env','GUID') }}"
  
  tasks:
  - name: Collection instance info
    os_server_info:
      cloud: "{{ guid }}-project"
    register: instances
  
  - name: Delete server instances
    os_server:
      name: "{{ instance.name }}"
      state: absent
    when: instance.metadata.AnsibleGroup == "haproxy_balancers"  or instance.metadata.AnsibleGroup == "backend_servers"  or instance.metadata.AnsibleGroup == "postgres_servers" 
    loop: "{{ instances.openstack_servers }}"
    loop_control:
      loop_var: instance
