---
- name: Play to setup in-memory-inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: in-memory-inventory
        
- name: Test connectivity
  hosts: haproxy_balancers,backend_servers,postgres_servers
  tasks:
    - name: test ping
      ping:



- name: Delete OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    guid: "{{ lookup('env','GUID') }}"
    
 
  tasks:
  
  - name: Include Instance variables
    include_vars: instances_vars.yml
  
  - name: Delete server instances
    os_server:
        name: "{{ instance.name }}"
        state: absent
    loop: "{{ instances }}"
    loop_control:
        loop_var: instance
