---
- name: Delete OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    guid: "{{ lookup('env','GUID') }}"
    
 
  tasks:
  
  - name: Include Instance variables
    include_vars: instances_vars.yml
  
  - name: Delete server instances
    os_server:
        name: "{{ instance.name }}"
        state: absent
    loop: "{{ instances }}"
    loop_control:
        loop_var: instance
