---
- name: Play to setup openstack instances
  hosts: localhost
  connection: local
  collections: openstack.cloud
  roles:
    - role: 
      - openstack_instances
      - in-memory-inventory
 
  
- name: Play to setup network members
  hosts: haproxy_balancers,backend_servers,postgres_servers
  gather_facts: true
  become: yes    
  roles:
    - role: network-member
    
- name: Test connectivity
  hosts: haproxy_balancers,backend_servers,postgres_servers
  tasks:
    - name: test ping
      ping:
      
- name: Play to setup postgres
  hosts: postgres_servers
  become: yes
  roles:
    - role: db-server
    
- name: Play to setup app-server
  hosts: backend_servers
  become: yes
  roles:
    - role: app-server
    

- name: Play to setup load_balancers
  hosts: haproxy_balancers
  become: yes
  roles:
    - role: load-balancer  
