---
- name: prueba database
  hosts: database_servers
  gather_facts: false
  
  tasks:
    - name: optener nombre
      command: hostname
      register: nombrehost
      
    - name: presentar nombres
      debug:
        var: nombrehost
    

- name: prueba app servers
  hosts: app_servers
  gather_facts: false

  tasks:
    - name: optener nombre
      command: hostname
      register: nombrehost
      
    - name: presentar nombres
      debug:
        var: nombrehost
        
- name: load balancers
  hosts: load_balancers
  gather_facts: false 


  vars:
    load_balancer_packages:
      - haproxy

  tags:
    - load_balancers

  tasks:
    - name: optener nombre
      command: hostname
      register: nombrehost
      
    - name: presentar nombres
      debug:
        var: nombrehost

- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true


  tasks:
    - name: optener nombre
      command: hostname
      register: nombrehost
      
    - name: presentar nombres
      debug:
        var: nombrehost



