---
- name: Deploy, configure, and populate Postgres 10
  hosts: localhost
  become: true
  gather_facts: false
  #tags:
    #- database_servers
  vars:
    
    postgres_rhel8_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    postgres_packages:
      - postgresql12 
      - postgresql12-server 
      - postgresql12-contrib 
      - postgresql12-libs
    postgres_library: python-psycopg2
    postgres_10_data_dir: /var/lib/pgsql/10/data
    postgres_10_bin_path: /usr/pgsql-10/bin
    postgres_service: postgresql-10.service
    postgres_port: 5432
    postgres_user: postgres
    postgres_users:
      - name: flask
        password: redhat
        database: flask_db
        state: present
        priv: ALL
    postgres_databases:
      - name: flask_db
        owner: flask
      - name: books_store
        owner: flask

  tasks:
    - name: deabilitar modulo postgre 
      command: dnf -qy module disable postgresql
 
    - name: installar
      yum:
        name: "{{ postgres_rhel8_repo }}"
        state: present
        disable_gpg_check: yes
      
  
    - name: Install Postgres packages
      package:
        name: "{{ __package }}"
        state: present
      loop:
        #- "{{ postgres_rhel8_repo }}"
        - "{{ postgres_packages }}"
        - "{{ postgres_library }}"
      loop_control:
        loop_var: __package 
