---
#- import_playbook: os_provision.yml
#- import_playbook: add_subscription.yml

- name: Play to setup in-memory-inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('ENV','GUID') }}"
    home: "{{ lookup('ENV','HOME') }}"
    internal_domain: "internal"
  #tasks:
  roles:
    - role: in-memory-inventory
        
- name: Test connectivity
  hosts: haproxy_balancers,backend_servers,postgres_servers
  tasks:
    - name: test ping
      ping:

