---
- name: Play to setup openstack instances
  hosts: localhost
  roles:
    - role: openstack_instances
    
- import_playbook: add_subscription.yml

- name: Play to setup in-memory-inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: in-memory-inventory
        
- name: Test connectivity
  hosts: haproxy_balancers,backend_servers,postgres_servers
  tasks:
    - name: test ping
      ping:
      
- name: Play to setup postgres
  hosts: postgres_servers
  become: yes
  roles:
    - role: db-server
    
- name: Play to setup app-server
  hosts: backend_servers
  become: yes
  roles:
    - role: app-server
    

- name: Play to setup load_balancers
  hosts: haproxy_balancers
  become: yes
  roles:
    - role: load-balancer  
