---
# - name: Play to setup in-memory-inventory
  # hosts: control   #control_node
  # collections: 
    # - openstack.cloud
  # gather_facts: false
  # roles:
    # - role: in-memory-inventory
    
- name: Play to setup network members
  hosts: haproxy_balancers,app_servers,postgres_servers
  collections: 
    - openstack.cloud
  gather_facts: true
  become: yes    
  roles:
    - role: network-member
