---
# - name: Play to setup in-memory-inventory
  # hosts: control   #control_node
  # collections: 
    # - openstack.cloud
  # gather_facts: false
  # roles:
    # - role: in-memory-inventory
    
- name: Play to setup network members
  hosts: haproxy_balancers,app_servers,postgres_servers
  gather_facts: true
  roles:
    - role: network-member
