---
- name: Create OpenStack Instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('ENV','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Show my fish 
      debug: 
        var: guid
