---
- name: Create OpenStack Instances
  hosts: all
  #connection: local
  gather_facts: false
  vars:
    guid: "{{ lookup('env','GUID') }}"
  tasks:
    - name: Include Instance variables
      include_vars: instances_vars.yml

    - name: Show my guid 
      debug: 
        var: guid
