---
- name: Create OpenStack Instances
  hosts: all
  #connection: local
  gather_facts: true
  vars:
    #guid: "{{ lookup('env','GUID') }}"
    #guid: 30cd
    
  tasks:
    - name: get GUID
      command: echo ${GUID}
      register: guid2

    - name: Show my guid 
      debug: 
        var: guid
