---
- name: Play to setup in-memory-inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: in-memory-inventory

- name: Play to setup postgres
  hosts: backend_servers
  become: yes
  roles:
    - role: app-server
