---
# - name: Play to setup in-memory-inventory
  # hosts: control   #control_node
  # gather_facts: false
  # roles:
    # - role: in-memory-inventory

- name: Play to setup postgres
  hosts: app_servers
  become: yes
  roles:
    - role: app-server
