---
- name: Play to setup in-memory-inventory
  hosts: control   #control_node
  gather_facts: false
  roles:
    - role: in-memory-inventory

- name: Play to setup load_balancers
  hosts: haproxy_balancers
  become: yes
  roles:
    - role: load-balancer 
